import { nissan_list } from './nissan';
import { suzuki_list } from './suzuki';
import { honda_list } from './honda';
import { toyota_list } from './toyota';
import { micro_list } from './micro';


export const models = {
    'Nissan': nissan_list,
    'Suzuki': suzuki_list,
    'Toyota': toyota_list,
    'Honda': honda_list,
    'MICRO': micro_list
  };




const nissan_models_eddition_list={
    "SUNNY":["sunny Edition 01"],
    "CARAVAN":["CARAVAN Edition 01"],
    "NV200":[" NV200 Edition 01"],
    "D21":[" D21 Edition 01"],
    "BLUEBIRD":["BLUEBIRD Edition 01"],
    "NAVARA":["NAVARA Edition 01"],
    "CEFIRO":["CEFIRO 01"],
    "VANETTE":["VANETTE 01"],
    "DATSUN":["DATSUN 01"],
    "PRESEA":["PRESEA 01"],
    "DAYZ":["DAYZ 01"],
    "MARCH":["MARCH 01"],
    "LARGO":["LARGO 01"],
    "CLIPPER":["CLIPPER 01"],
    "FB 15":["FB 15 01"],
    "X TRAIL":["X TRAIL 01"],
    "SERENA":["SERENA 01"],
    "TIIDA":["TIIDA 01"],
    "WINGROAD":["WINGROAD 01"],
    "LEAF":["LEAF 01"],
    "PRIMERA":["PRIMERA 01"],
    "AD WAGON":["AD WAGON 01"],
    "PULSAR":["PULSAR 01"],
    "FB 13":["FB 13 01"],
    "B11":["B11 01"],
    "HOMY":["HOMY 01"],
    "B310":["B310 01"],
    "PATROL":["PATROL 01"],
    "N 16":["N 16 01"],
    "FB 14":["FB 14 01"],
    "DOUBLE CAB":["DOUBLE CAB 01"]
}


const suzuki_models_eddition_list={
  "ZEN":["ZEN Suzuki 01"],
  "VITARA":["VITARA Suzuki 01"],
  "SX":["SX Suzuki 01"],
  "SWIFT":["SWIFT Suzuki 01"],
  "SPACIA":["SPACIA Suzuki 01"],
  "SOLIO":["SOLIO Suzuki 01"],
  "RITZ":["RITZ Suzuki 01"],
  "OMNI":["OMNI Suzuki 01"],
  "LIANA":["LIANA Suzuki 01"],
  "KEI":["KEI Suzuki 01"],
  "JIMNY":["JIMNY Suzuki 01"],
  "IGNIS":["IGNIS Suzuki 01"],
  "HUSTLER":["HUSTLER Suzuki 01"],
  "GRAND VITARA":["GRAND VITARA Suzuki 01"],
  "EVERY":["EVERY Suzuki 01"],
  "ESTILO":["ESTILO Suzuki 01"],
  "ESTEEM":["ESTEEM Suzuki 01"],
  "ESCUDO":["ESCUDO Edition Suzuki 01"],
  "DZIRE":["DZIRE Suzuki 01"],
  "CULTUS":["CULTUS Suzuki 01"],
  "CARRY":["CARRY Suzuki 01"],
  "AERIO":["AERIO Suzuki 01"],
  "WAGON R STINGRAY":["WAGON R STINGRAY Suzuki 01"],
  "WAGON R FZ SAFETY":["WAGON R FZ SAFETY Suzuki 01"],
  "WAGON R FZ":["WAGON R FZ Suzuki 01"],
  "WAGON R FX SAFETY":["Edition Suzuki 01"],
  "WAGON R FX":["Edition Suzuki 01"],
  "WAGON R J-STYLE":["Edition Suzuki 01"],
  "WAGON R STINGRAY SAFETY":["Edition Suzuki 01"],
  "WAGON R INDIAN":["Edition Suzuki 01"],
  "MARUTI 800":["Edition Suzuki 01"],
  "CELERIO ZXI AMT":["Edition Suzuki 01"],
  "CELERIO LXI":["Edition Suzuki 01"],
  "CELERIO VXI":["Edition Suzuki 01"],
  "BALENO RS TURBO":["Edition Suzuki 01"],
  "BALENO ZETA CVT":["Edition Suzuki 01"],
  "ALTO JAPAN":["Edition Suzuki 01"],
  "ALTO VXI":["Edition Suzuki 01"],
  "ALTO LXI":["Edition Suzuki 01"],
  "ALTO K10 VXI":["Edition Suzuki 01"],
  "ALTO K10 LXI":["Edition Suzuki 01"],
  "A STAR VXI":["Edition Suzuki 01"],
  "A STAR LXI":["Edition Suzuki 01"],
  "SWIFT VXI":["Edition Suzuki 01"],
  "SPACIA CUSTOM Z":["Edition Suzuki 01"],
  "CELERIO ZXI":["Edition Suzuki 01"],
  "S CROSS SPORTS":["Edition Suzuki 01"],
  "ESCUDO VITARA G":["Edition Suzuki 01"],
  "SPACIA G GRADE":["Edition Suzuki 01"],
  "CELERIO VXI AMT":["Edition Suzuki 01"],
  "ESTILO ZEN":["Edition Suzuki 01"],
  "VITARA G":["Edition Suzuki 01"],
  "ESTILO VXI":["Edition Suzuki 01"],
  "ESTEEM" :["Edition Suzuki 01"],
  "ALTO SPORT":["Edition Suzuki 01"],
  "AERIO" :["Edition Suzuki 01"],
  "SWIFT DZIRE":["Edition Suzuki 01"],
  "SWIFT BITTLE SHIFT":["Edition Suzuki 01"],
  "EVERY SEMI JOIN":["Edition Suzuki 01"],
  "GYPSY":["Edition Suzuki 01"],
  "SWIFT ZC11":["Edition Suzuki 01"],
  "BALENO TURBO":["Edition Suzuki 01"],
  "SWIFT KEI":["Edition Suzuki 01"],
  "BALENO":["Edition Suzuki 01"], 
  "SWIFT 4 WAY TURBO":["Edition Suzuki 01"],
  "SWIFT RS TURBO":["Edition Suzuki 01"],
  "SWIFT RS HYBRID":["Edition Suzuki 01"],
}


const honda_models_eddition_list={
  "HIACE":["HIACE Honda 1"],
  "HILUX":["HILUX Honda 1"],
  "PREMIO":["PREMIO Honda 1"],
  "CHR":["CHR Honda 1"],
  "RUSH":["RUSH Honda 1"],
  "ALLION":["ALLION Honda 1"],
  "RAIZE":["RAIZE Honda 1"],
  "AXIO":["AXIO Honda 1"],
  "NOAH":["NOAH Honda 1"],
  "PRIUS":["PRIUS Honda 1"],
  "YARIS":["YARIS Honda 1"],
  'AQUA':["AQUA Honda 1"],
  "RAV4":["RAV4 Honda 1"],
  'VITZ':["VITZ Honda 1"],
  "ROOMY":["ROOMY Honda 1"],
  "TANK":["TANK Honda 1"],
  "MARK II":["MARK II Honda 1"],
  "CAMRY":["CAMRY Honda 1"],
  "COROLLA":["COROLLA Honda 1"],
  "TOWNACE":["TOWNACE Honda 1"],
  "AVANZA":["Edistion Honda 1"],
  "PASSO":["Edistion Honda 1"],
  "WIGO":["Edistion Honda 1"],
  "IST":["Edistion Honda 1"],
  "LH113":["Edistion Honda 1"],
  "BELTA":["Edistion Honda 1"],
  'PIXIS':["Edistion Honda 1"],
  'LITEACE':["Edistion Honda 1"],
  "CAMI":["Edistion Honda 1"],
  'VIOS':["Edistion Honda 1"],
  "REGIUS":["Edistion Honda 1"],
  "CARINA":["Edistion Honda 1"],
  "STARLET":["Edistion Honda 1"],
  "SPRINTER":["Edistion Honda 1"],
  "GLANZA V":["Edistion Honda 1"],
  "CORONA":["Edistion Honda 1"],
  "AE100":["Edistion Honda 1"],
  "CR27":["Edistion Honda 1"],
  'PLATZ':["Edistion Honda 1"],
  "CORSA":["Edistion Honda 1"],
  "MARINO":["Edistion Honda 1"],
  "VAN":["Edistion Honda 1"],
  "CHASER":["Edistion Honda 1"],
  "SOLUNA":["Edistion Honda 1"],
  "CYNOS":["Edistion Honda 1"],
  "CALDINA":["Edistion Honda 1"],
  "VISTA":["Edistion Honda 1"],
  "TERCEL":["Edistion Honda 1"],
  "DUET":["Edistion Honda 1"],
  "CAR":["Edistion Honda 1"],
  "CRESSIDA":["Edistion Honda 1"],
  "CROWN":["Edistion Honda 1"],
  "VANGUARD":["Edistion Honda 1"],
  "VEROSSA":["Edistion Honda 1"],
  "LH61":["Edistion Honda 1"],
  "RAUM":["Edistion Honda 1"],
  "LH20":["Edistion Honda 1"],
  "FORTUNER":["Edistion Honda 1"],
  "HARRIER":["Edistion Honda 1"],
  "GRAND HIACE":["Edistion Honda 1"],
  "AXIA":["Edistion Honda 1"],
  "ECHO":["Edistion Honda 1"],
  "LEXUS":["Edistion Honda 1"]  
}

const toyota_models_eddition_list={
  "TOYOTA":["Edistion Toyota 1"]
}

const micro_models_eddition_list={
  "MICRO":["Edistion Micro 1"]
}


export const editionlist = {
  'Nissan': nissan_models_eddition_list,
  'Suzuki': suzuki_models_eddition_list,
  'Toyota': toyota_models_eddition_list,
  'Honda': honda_models_eddition_list,
  'MICRO': micro_models_eddition_list
};
