export const suzuki_list=[
        "ZEN",
        "VITARA",
        "SX",
        "SWIFT",
        "SPACIA",
        "SOLIO",
        "RITZ",
        "OMNI",
        "LIANA",
        "KEI",
        "JIMNY",
        "IGNIS",
        "HUSTLER",
        "GRAND VITARA",
        "EVERY",
        "ESTILO",
        "ESTEEM",
        "ESCUDO",
        "DZIRE",
        "CULTUS",
        "CARRY",
        "AERIO",
        "WAGON R STINGRAY",
        "WAGON R FZ SAFETY",
        "WAGON R FZ",
        "WAGON R FX SAFETY",
        "WAGON R FX",
        "WAGON R J-STYLE",
        "WAGON R STINGRAY SAFETY",
        "WAGON R INDIAN",
        "MARUTI 800",
        "CELERIO ZXI AMT",
        "CELERIO LXI",
        "CELERIO VXI",
        "BALENO RS TURBO",
        "BALENO ZETA CVT",
        "ALTO JAPAN",
        "ALTO VXI",
        "ALTO LXI",
        "ALTO K10 VXI",
        "ALTO K10 LXI",
        "A STAR VXI",
        "A STAR LXI",
        "SWIFT VXI",
        "SPACIA CUSTOM Z",
        "CELERIO ZXI",
        "S CROSS SPORTS",
        "ESCUDO VITARA G",
        "SPACIA G GRADE",
        "CELERIO VXI AMT",
        "ESTILO ZEN",
        "VITARA G",
        "ESTILO VXI",
        "ESTEEM" ,
        "ALTO SPORT",
        "AERIO" ,
        "SWIFT DZIRE",
        "SWIFT BITTLE SHIFT",
        "EVERY SEMI JOIN",
        "GYPSY",
        "SWIFT ZC11",
        "BALENO TURBO",
        "SWIFT KEI",
        "BALENO", 
        "SWIFT 4 WAY TURBO",
        "SWIFT RS TURBO",
        "SWIFT RS HYBRID"
]